import * as React from "react";
import { styled } from "@mui/material/styles";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import CssBaseline from "@mui/material/CssBaseline";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import IconButton from "@mui/material/IconButton";
import Paper from "@mui/material/Paper";
import Fab from "@mui/material/Fab";
import List from "@mui/material/List";
import MenuIcon from "@mui/icons-material/Menu";
import AddIcon from "@mui/icons-material/Add";
import SearchIcon from "@mui/icons-material/Search";
import Drawer from "@mui/material/Drawer";
import Divider from "@mui/material/Divider";
import ListItem from "@mui/material/ListItem";
import { Backpack } from "./backpack";
import DeleteForeverIcon from "@mui/icons-material/DeleteForever";
import TextField from '@mui/material/TextField';
import { Button } from "@mui/material";
const messages = [
  //   {
  //     id: 1,
  //     primary: 'Brunch this week?',
  //     secondary: "I'll be in the neighbourhood this week. Let's grab a bite to eat",
  //     person: '/static/images/avatar/5.jpg',
  //   },
  //   {
  //     id: 2,
  //     primary: 'Birthday Gift',
  //     secondary: `Do you have a suggestion for a good present for John on his work
  //       anniversary. I am really confused & would love your thoughts on it.`,
  //     person: '/static/images/avatar/1.jpg',
  //   },
  //   {
  //     id: 3,
  //     primary: 'Recipe to try',
  //     secondary: 'I am try out this new BBQ recipe, I think this might be amazing',
  //     person: '/static/images/avatar/2.jpg',
  //   },
  //   {
  //     id: 4,
  //     primary: 'Yes!',
  //     secondary: 'I have the tickets to the ReactConf for this year.',
  //     person: '/static/images/avatar/3.jpg',
  //   },
  //   {
  //     id: 5,
  //     primary: "Doctor's Appointment",
  //     secondary: 'My appointment for the doctor was rescheduled for next Saturday.',
  //     person: '/static/images/avatar/4.jpg',
  //   },
  //   {
  //     id: 6,
  //     primary: 'Discussion',
  //     secondary: `Menus that are generated by the bottom app bar (such as a bottom
  //       navigation drawer or overflow menu) open as bottom sheets at a higher elevation
  //       than the bar.`,
  //     person: '/static/images/avatar/5.jpg',
  //   },
  //   {
  //     id: 7,
  //     primary: 'Summer BBQ',
  //     secondary: `Who wants to have a cookout this weekend? I just got some furniture
  //       for my backyard and would love to fire up the grill.`,
  //     person: '/static/images/avatar/1.jpg',
  //   },
];

const StyledFab = styled(Fab)({
  position: "absolute",
  zIndex: 1,
  top: -30,
  left: 0,
  right: 0,
  margin: "0 auto",
});

export function BottomAppBar() {
  const [state, setState] = React.useState({
    top: false,
    left: false,
    bottom: false,
    right: false,
  });

  const toggleDrawer = (anchor, open) => (event) => {
    if (
      event.type === "keydown" &&
      (event.key === "Tab" || event.key === "Shift")
    ) {
      return;
    }

    setState({ ...state, [anchor]: open });
  };
  const addCourse = () => { };
  return (
    <React.Fragment>
      <CssBaseline />
      <Paper square sx={{ pb: "50px" }}>
        <Typography
          variant="h5"
          gutterBottom
          component="div"
          sx={{ p: 2, pb: 0 }}
        >
          Backpack
        </Typography>
        <List
          sx={{
            mb: 2,
            display: "flex",
            flexWrap: "wrap",
            alignItems: "flex-start",
          }}
        >
          {/* {messages.map(() => ( */}
          <Backpack />
          <Backpack />
          <Backpack />
          <Backpack />
          <Backpack />
          <Backpack />
          <Backpack />
          <Backpack />
          <Backpack />
          {/* ))} */}
        </List>
      </Paper>
      <AppBar position="sticky" color="primary" sx={{ bottom: 0 }}>
        <Toolbar>
          <IconButton color="inherit" aria-label="open drawer">
            <MenuIcon />
          </IconButton>
          <StyledFab
            onClick={toggleDrawer("bottom", true)}
            color="secondary"
            aria-label="add"
          >
            <AddIcon />
          </StyledFab>
          <Box sx={{ flexGrow: 1 }} />
          <IconButton color="inherit">
            <SearchIcon />
          </IconButton>

          <IconButton color="inherit">
            <React.Fragment key={"bottom"}>
              <Drawer
                anchor={"bottom"}
                open={state["bottom"]}
                onClose={toggleDrawer("bottom", false)}
              >
                <Typography>Add A Course</Typography>
                <Box sx={{ width: 'auto'}} role="presentation">
                  <List sx={{display:'flex',flexDirection:'row',justifyContent:'flex-start'}}>
                    <ListItem>
                    <TextField required label="Course   Name" variant="outlined" />  
                    </ListItem>
                    <ListItem >
                    <TextField required label="Course Id: 19AD451" variant="outlined" />  
                    </ListItem>
                    <ListItem >
                    <TextField required label="Course Batch: 2020-24" variant="outlined" />  
                    </ListItem>
                    <ListItem >
                      <Button variant="contained" color="success" >Submit</Button>
                    </ListItem>
                  </List>
                  <Divider />
                </Box>
              </Drawer>
            </React.Fragment>
          </IconButton>

          <IconButton color="inherit">
            <DeleteForeverIcon />
          </IconButton>
        </Toolbar>
      </AppBar>
    </React.Fragment>
  );
}
